CREATE TABLE IF NOT EXISTS pulls (
    id SERIAL PRIMARY KEY,
    remote_id VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
)
